import { jsPDF } from 'jspdf';
import { TOYOTA_VEHICLES } from './toyotaData';
import { TOYOTA_VEHICLE_DETAILS } from './toyotaDetailsData';

export const downloadSpecSheet = async (vehicleId: string, getAssetUrl: (path: string) => string) => {
  const vehicle = TOYOTA_VEHICLES.find(v => v.id === vehicleId);
  const details = TOYOTA_VEHICLE_DETAILS[vehicleId];
  if (!vehicle || !details) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const getBase64FromUrl = async (url: string): Promise<string> => {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  };

  try {
    const krishLogoBase64 = await getBase64FromUrl(getAssetUrl('krish_toyota_logo.png'));
    const toyotaLogoBase64 = await getBase64FromUrl(getAssetUrl('toyota_logo.png'));

    let pageNum = 1;

    const drawHeader = (pdf: typeof doc, isFirstPage: boolean) => {
      pdf.setFillColor(11, 15, 25);
      pdf.rect(0, 0, 210, 42, 'F');
      pdf.addImage(krishLogoBase64, 'PNG', 15, 10, 48, 12);
      pdf.addImage(toyotaLogoBase64, 'PNG', 165, 8, 30, 21);

      if (isFirstPage) {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(22);
        pdf.setTextColor(255, 255, 255);
        pdf.text(vehicle.name.toUpperCase(), 15, 30);

        pdf.setFont('helvetica', 'italic');
        pdf.setFontSize(10);
        pdf.setTextColor(200, 200, 200);
        pdf.text(details.hero.tagline, 15, 36);
      } else {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(14);
        pdf.setTextColor(255, 255, 255);
        pdf.text(`${vehicle.name.toUpperCase()} - SPECIFICATION SHEET`, 15, 30);
      }
    };

    const drawFooter = (pdf: typeof doc, page: number) => {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Krish Toyota Premium Showroom', 15, 288);
      pdf.text(`Page ${page}`, 195, 288, { align: 'right' });
    };

    drawHeader(doc, true);
    drawFooter(doc, pageNum);

    let y = 50;

    doc.setFillColor(245, 245, 245);
    doc.rect(15, y, 180, 10, 'F');
    doc.setDrawColor(220, 220, 220);
    doc.rect(15, y, 180, 10, 'D');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(225, 6, 0);
    doc.text('CONSULTANT:', 20, y + 6.5);
    doc.setTextColor(50, 50, 50);
    doc.setFont('helvetica', 'normal');
    doc.text(`Salath Joseph    |    Phone: +91 88380 32478`, 47, y + 6.5);

    y += 18;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(225, 6, 0);
    doc.text('1. VEHICLE OVERVIEW', 15, y);
    
    doc.setDrawColor(225, 6, 0);
    doc.setLineWidth(0.5);
    doc.line(15, y + 1.5, 75, y + 1.5);

    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    
    const introLines = doc.splitTextToSize(details.hero.introduction, 180);
    doc.text(introLines, 15, y);
    y += (introLines.length * 5) + 4;

    doc.setFillColor(250, 250, 250);
    doc.rect(15, y, 180, 18, 'F');
    doc.rect(15, y, 180, 18, 'D');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('CATEGORY:', 20, y + 6);
    doc.text('PLATFORM:', 20, y + 12);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(50, 50, 50);
    doc.text(details.overview.category, 45, y + 6);
    doc.text(details.overview.platform, 45, y + 12);

    y += 28;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(225, 6, 0);
    doc.text('2. ENGINE & PERFORMANCE', 15, y);
    doc.line(15, y + 1.5, 75, y + 1.5);

    y += 8;

    const renderSpecRow = (pdf: typeof doc, label: string, val: string, currY: number) => {
      pdf.setFillColor(253, 253, 253);
      pdf.rect(15, currY, 180, 8, 'F');
      pdf.setDrawColor(240, 240, 240);
      pdf.rect(15, currY, 180, 8, 'D');
      
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(9);
      pdf.setTextColor(110, 110, 110);
      pdf.text(label, 20, currY + 5.5);

      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(40, 40, 40);
      pdf.text(val, 70, currY + 5.5);
    };

    renderSpecRow(doc, 'Engine Configuration', details.performance.engineType, y); y += 8;
    renderSpecRow(doc, 'Displacement', details.performance.displacement, y); y += 8;
    renderSpecRow(doc, 'Maximum Power', details.performance.power, y); y += 8;
    renderSpecRow(doc, 'Maximum Torque', details.performance.torque, y); y += 8;
    renderSpecRow(doc, 'Transmission Type', details.performance.transmission, y); y += 8;
    renderSpecRow(doc, 'Drivetrain', details.performance.drivetrain, y); y += 8;
    renderSpecRow(doc, 'Fuel Technology', vehicle.specs.fuelType, y); y += 8;

    y += 12;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(225, 6, 0);
    doc.text('3. DIMENSIONS & CHASSIS', 15, y);
    doc.line(15, y + 1.5, 75, y + 1.5);

    y += 8;
    renderSpecRow(doc, 'Overall Length', details.dimensions.length, y); y += 8;
    renderSpecRow(doc, 'Overall Width', details.dimensions.width, y); y += 8;
    renderSpecRow(doc, 'Overall Height', details.dimensions.height, y); y += 8;
    renderSpecRow(doc, 'Wheelbase', details.dimensions.wheelbase, y); y += 8;
    renderSpecRow(doc, 'Ground Clearance', details.dimensions.clearance, y); y += 8;
    renderSpecRow(doc, 'Front Suspension', details.chassis.frontSusp, y); y += 8;
    renderSpecRow(doc, 'Rear Suspension', details.chassis.rearSusp, y); y += 8;

    doc.addPage();
    pageNum += 1;
    drawHeader(doc, false);
    drawFooter(doc, pageNum);

    y = 52;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(225, 6, 0);
    doc.text('4. SAFETY SYSTEMS & ADAS', 15, y);
    doc.line(15, y + 1.5, 80, y + 1.5);

    y += 8;
    renderSpecRow(doc, 'Airbags system', details.safety.airbags, y); y += 8;
    renderSpecRow(doc, 'Stability Control (VSC)', details.safety.vsc, y); y += 8;
    renderSpecRow(doc, 'ABS & EBD Systems', details.safety.abs, y); y += 8;
    renderSpecRow(doc, 'Hill Start Assist', details.safety.hillAssist, y); y += 8;

    if (details.safety.adas.hasAdas) {
      y += 8;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(225, 6, 0);
      doc.text('Toyota Safety Sense (ADAS Level 2):', 15, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);

      const adasText = `• Pre-Collision System: ${details.safety.adas.preCollision}\n• Adaptive Cruise Control: ${details.safety.adas.acc}\n• Lane Trace Assist: ${details.safety.adas.lka}\n• Blind Spot Monitor: ${details.safety.adas.bsm}`;
      const adasLines = doc.splitTextToSize(adasText, 180);
      doc.text(adasLines, 15, y);
      y += (adasLines.length * 4.5) + 4;
    } else {
      y += 4;
    }

    y += 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(225, 6, 0);
    doc.text('5. VEHICLE TRIM VARIANTS', 15, y);
    doc.line(15, y + 1.5, 75, y + 1.5);

    y += 8;
    details.variants.forEach((v) => {
      if (y > 255) {
        doc.addPage();
        pageNum += 1;
        drawHeader(doc, false);
        drawFooter(doc, pageNum);
        y = 52;
      }

      doc.setFillColor(250, 250, 250);
      doc.rect(15, y, 180, 16, 'F');
      doc.rect(15, y, 180, 16, 'D');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(225, 6, 0);
      doc.text(v.name, 20, y + 5.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(100, 100, 100);
      doc.text(`${v.fuelType}  |  ${v.transmission}  |  ${v.seating}`, 20, y + 11.5);

      const keyFeats = v.features.slice(0, 3).join(', ');
      doc.text(`Key Features: ${keyFeats}`, 95, y + 8.5);

      y += 20;
    });

    y += 2;

    if (y > 240) {
      doc.addPage();
      pageNum += 1;
      drawHeader(doc, false);
      drawFooter(doc, pageNum);
      y = 52;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(225, 6, 0);
    doc.text('6. WARRANTY & BENEFITS', 15, y);
    doc.line(15, y + 1.5, 75, y + 1.5);

    y += 8;
    renderSpecRow(doc, 'Standard Warranty', details.ownership.warranty, y); y += 8;
    renderSpecRow(doc, 'Service Intervals', details.ownership.intervals, y); y += 8;
    renderSpecRow(doc, 'Maintenance Schedule', details.ownership.schedule, y); y += 8;

    doc.save(`Krish-Toyota-${vehicle.name.replace(/\s+/g, '-')}-Spec-Sheet.pdf`);
  } catch (error) {
    console.error('Failed to generate PDF:', error);
  }
};
